### ISSUE TITLE
ZLIB 1.2.9 not found

### ISSUE THREAD

**Issue by uriel1998** [conoro/tiktok-rss#1]
NOTE:  I am a TOTAL noob with AWS Lambda.  Your patience is appreciated.

I set up serverless, followed the README instructions, and I get this error when trying to access any (valid) user's feed:

XML Parsing Error: not well-formed
Location: https://BLAHBLAH.execute-api.us-east-1.amazonaws.com/dev/rss?user=username
Line Number 1, Column 1:
{errorType=Runtime.UnhandledPromiseRejection, errorMessage=Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /var/task/node_modules/canvas/build/Release/libpng16.so.16), trace=["Runtime.UnhandledPromiseRejection: Error: \/lib64\/libz.so.1: version `ZLIB_1.2.9' not found (required by \/var\/task\/node_modules\/canvas\/build\/Release\/libpng16.so.16)","    at process.<anonymous> (file:\/\/\/var\/runtime\/index.mjs:1250:17)","    at process.emit (node:events:513:28)","    at emit (node:internal\/process\/promises:140:20)","    at processPromiseRejections (node:internal\/process\/promises:274:27)","    at processTicksAndRejections (node:internal\/process\/task_queues:97:32)"]}
^

I additionally tried compiling zlib 1.2.9 and moving `libz.so.1.2.9` to `./node_modules/canvas/build/Release/libz.so.1` but I do not wish to replace the system install since it'll break a bunch of packages.

Is the only recourse building in a VM (with 1.2.9)?  Is there a bit of code or requirements I could change instead?

**Comment by conoro** [comment]
Sorry this hasn't been maintained due to lots of problems with accessing TikTok. I'll archive it. 

However this is still working (mostly!) for me:

https://github.com/conoro/tiktok-rss-flat
